
export type CoreExerciseKeys = 
'standingChop'
| 'standingLift'
| 'kneelingCableCrunch'
| 'kneelingChop'
| 'kneelingLift'
| 'shoulderTapPlank'
| 'plank'
| 'plankRun'
| 'sprinterCrunch'
| 'halfKneelingChop'
| 'cableSideBends'
| 'situps'
| 'weightedSitUps'
| 'crunches'
| 'weightedCrunches'
| 'mountainClimber'
| 'russianTwists'
| 'sidePlank'
| 'legRaise'
| 'deadBug'
| 'overheadMarches'
| 'lyingDownLegRaises'