
export type MobilityExerciseKeys = 
'inchWorm'
| '9090'
| 'reverseSnowAngel'
| 'bookOpener'
| 'deepSquatThoracicRotation'
| 'proneScorpionKick'
| 'hipRocking'
| 'birdDog'
| 'hipRotation'
| 'supineWiper'
| 'hamstringStretch'
| 'flexorStretch'
| 'prayerThoracicMobility'
| 'scmActivation'
| 'stretchHold'
